## NumPy arrays

In [1]:
import numpy as np

In [3]:
# Create a np array.
mylist = [1, 2, 3]

In [4]:
type(mylist)

list

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
mylist

[1, 2, 3]

In [7]:
myarr = np.array(mylist)

In [8]:
type(myarr)

numpy.ndarray

In [9]:
mymatrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
mymatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
# np new to print as a matrix
np.array(mymatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
# Bootstrap an array
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# Include a step size
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [14]:
# 1D vector of 0s, 0. indicates floating point for precision.
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
# Rows are made first then columns
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
# Return evenly spaced numbers over a specified interval
# - Give me 3 evenly spaced numbers between 0-10
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [21]:
# - 0-10 is 11 numbers!
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [23]:
np.linspace(0, 5, 21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [24]:
len(np.linspace(0, 5, 21))

21

In [25]:
# Create identity matrix (has same number of cols and rows)
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
# Give a shape and will give random values.
np.random.rand(1)

array([0.99376977])

In [30]:
np.random.rand(5, 6)

array([[0.96225426, 0.1361283 , 0.38947318, 0.34456   , 0.36739769,
        0.11637885],
       [0.47648292, 0.56044383, 0.4892648 , 0.74887783, 0.3077208 ,
        0.50405639],
       [0.22726009, 0.78180296, 0.50031443, 0.13961123, 0.93649633,
        0.57684606],
       [0.72515236, 0.02200644, 0.6926768 , 0.45725635, 0.26605807,
        0.30293518],
       [0.30712006, 0.64225432, 0.88774294, 0.70022659, 0.07540448,
        0.88136549]])

In [31]:
np.random.rand(5, 2)

array([[0.4902897 , 0.04806045],
       [0.62372488, 0.0337647 ],
       [0.07419129, 0.59308059],
       [0.73378295, 0.07712176],
       [0.28434956, 0.80404258]])

In [32]:
# Standard normal distribution (we can get negative values but values closer to 0 are more likely)
np.random.randn(10)

array([-1.14131085, -0.86154579, -2.70218097, -0.50370531,  1.21292199,
       -1.34487853, -1.86240631,  1.13179887, -0.19623558,  0.93726389])

In [33]:
np.random.randn(2, 3)

array([[-0.48798457,  1.03473096, -1.04496877],
       [ 1.93690055,  0.19890148,  1.93387988]])

In [38]:
# Returns back random integers (give 5 random ints between 0 - 101)
np.random.randint(0, 101, 5)

array([49, 93,  3, 65, 47])

In [40]:
# Last param can be a tuple for matrix
np.random.randint(0, 101, (4, 5))

array([[10, 51, 25,  9, 88],
       [80, 78, 17, 85, 82],
       [83, 97, 33, 88, 42],
       [89, 33,  5, 45, 72]])

In [44]:
# Set a seed for random state. (set a particular set of random numbers, we can repeat random distributions)
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [45]:
arr = np.arange(0, 25)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
# We can reshape datastructures
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
# Must equal original elements.
arr.reshape(4, 5)

ValueError: cannot reshape array of size 25 into shape (4,5)

In [50]:
ranarr = np.random.randint(0, 101, 10)

In [51]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [52]:
# Max value
ranarr.max()

99

In [53]:
ranarr.min()

2

In [54]:
# index 
ranarr.argmax()

5

In [55]:
ranarr.argmin()

7

In [56]:
# Get the data type of the array
ranarr.dtype

dtype('int32')

In [57]:
# Shape is an attribute of an existing array (25,) indicates one long row not one long column
arr.shape

(25,)

In [58]:
arr = arr.reshape(5, 5)

In [59]:
arr.shape

(5, 5)

In [60]:
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [61]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])