# Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
# Goes up to but not including.
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [9]:
# Do not need to know how long the array is
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [11]:
# Ability to broadcast. we can broadcast a single value across a large number of values.
arr[0:5] = 100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
arr = np.arange(0, 11)

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
slice_of_arr = arr[:5]

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [22]:
slice_of_arr[:] = 99

In [23]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [24]:
# A slice is not a copy of the original array
arr_copy = arr.copy()

In [25]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [26]:
arr_copy[:] = 100

In [27]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [28]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [29]:
arr2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [30]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
arr2d.shape

(3, 3)

In [33]:
arr2d[0]

array([ 5, 10, 15])

In [34]:
arr2d[1]

array([20, 25, 30])

In [35]:
arr2d[0][0]

5

In [36]:
arr2d[1][1]

25

In [37]:
# Equivaluent to seperate definition
arr2d[1, 1]

25

In [39]:
# Get the first two rows and the last two columns using same syntax
arr2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [40]:
# Conditional selection
arr = np.arange(1, 11)

In [41]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
# Returns where index location matches up with the original data
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [43]:
boolarr = arr > 4

In [44]:
boolarr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [45]:
# Can use bool array to filter! by indexing by the conditional array
# The finesse!
arr[boolarr]

array([ 5,  6,  7,  8,  9, 10])

In [46]:
# Simplified (simple way to apply a filter)
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [47]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

total_rolls_over_two = len(dice_rolls[dice_rolls > 2])

print(total_rolls_over_two)

19
