## NumPy arrays

In [1]:
import numpy as np

In [3]:
# Create a np array.
mylist = [1, 2, 3]

In [4]:
type(mylist)

list

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
mylist

[1, 2, 3]

In [7]:
myarr = np.array(mylist)

In [8]:
type(myarr)

numpy.ndarray

In [9]:
mymatrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
mymatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
# np new to print as a matrix
np.array(mymatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
# Bootstrap an array
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])